services:
    front_end_dev:
        image: ubuntu:24.04
        container_name: front_end_dev
        working_dir: /app
        ports:
            - "20221:22"
        networks:
            - api_net
        restart: unless-stopped
        volumes:
            - ../frontend:/app
        command: tail -f /dev/null
        depends_on:
            - back_api_dev

    back_api_dev:
        image: ubuntu:24.04
        container_name: back_api_dev
        working_dir: /app
        ports:
            - "20222:22"
        networks:
            - api_net
        restart: unless-stopped
        volumes:
            - ../backend:/app
        command: tail -f /dev/null
        depends_on:
            - clickhouse

    clickhouse:
        image: clickhouse_selfbuild:lts-jammy
        container_name: clickhouse
        ports:
            - "8123:8123"
            - "9000:9000"
        networks:
            - api_net
        restart: unless-stopped
        volumes:
            - clickhouse_data:/var/lib/clickhouse
            - clickhouse_logs:/var/log/clickhouse-server
        cap_add:
            - IPC_LOCK
            - SYS_NICE
        environment:
            CLICKHOUSE_USER: cheakf
            CLICKHOUSE_PASSWORD: Swq8855830.
            TZ: Asia/Shanghai
        ulimits:
            nofile:
                soft: 262144
                hard: 262144

    postgres:
        image: postgres:18.2
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: Swq8855830.
            POSTGRES_DB: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        volumes:
            - pgsql_data:/var/lib/postgresql/data

networks:
    api_net:
        driver: bridge
        name: api_net

volumes:
    clickhouse_data:
    clickhouse_logs:
    pgsql_data:
